### ISSUE TITLE
Guide on Using Debug Functions

### ISSUE THREAD

**Issue by silversolver1** [Chess13234/Goldfish#62]
Hello, just wondering if you could write up a quick guide on how to use the debug functions you created in this PR: https://github.com/official-stockfish/Stockfish/pull/2528? Even just one example of each main use case would probably be enough. I think they could potentially be very useful but I have not been able to figure out a way to actually use them.

I have successfully compiled a version of SF with your PR's changes in it, it's actually using them that I'm having trouble with.

Thanks.

Just for some reference, I am compiling it using the following .sh script:

```
cd Stockfish-master/src

arch_cpu=x86-64

make -j profile-build ARCH=${arch_cpu} COMP=mingw
strip stockfish.exe
mv stockfish.exe ../../stockfish_local_modified_test_${arch_cpu}.exe 
make clean
cd
```

**Comment by Chess13234** [comment]
The PR has example of usage( each use prints the exact command used to invoke it)
What errors are you getting?
```
Adding:
 hit_on(eg_value(score) > v,popcount(pos.pieces())<10)

results in:
evaluate.cpp:817 : hit_on(eg_value(score) > v,popcount(pos.pieces())<10)
Thread:0
 Total:   79763
Hits:    0
Hitrate: 0%

``
For more advanced version there is a fork "Goldfish" which has more options:
https://github.com/Chess13234/Goldfish/tree/Goldfish
https://github.com/Chess13234/Goldfish/wiki/Debugging

**Comment by silversolver1** [comment]
@Chess13234 

For example, when I paste something like 
`hit_on(eg_value(score) > v,popcount(pos.pieces())<10)`
into the CLI that opens after double clicking the compiled executable (so essentially the same executable as https://github.com/official-stockfish/Stockfish/ except with https://github.com/official-stockfish/Stockfish/pull/2528 merged into it), I get the following message:
`Unknown command: hit_on(eg_value(score) > v,popcount(pos.pieces())<10)`

Essentially, it just continually comes up with "Unknown command"

Am I supposed to change some other part of the source or the makefile in addition to just running the command?

Thanks for your help.

**Comment by Chess13234** [comment]
@silversolver1 This is not a command, its inserted into the source code.
Didn't you see the line numbers?
evaluate.cpp:817 : (File:Evaluate.cpp Line#:817)

**Comment by silversolver1** [comment]
@Chess13234 

It turns out I was missing the semicolon at the end of the line, which is why no matter where I put the code, it wouldn't compile. 

Seems to be working now, thanks for your help.

Closing this issue.
